[[quarto]]
arch = "aarch64"
git-tree-sha1 = "e68bee4bb0c5f3be695cbee7da78e1f468b87d6a"
os = "macos"

    [[quarto.download]]
    sha256 = "f2399b1e1f29bdebfdfc831f45771ea9ccd71682740279e50159a06a2d44643d"
    url = "https://github.com/JuliaBinaryWrappers/quarto_jll.jl/releases/download/quarto-v1.5.57+1/quarto.v1.5.57.aarch64-apple-darwin.tar.gz"
[[quarto]]
arch = "aarch64"
git-tree-sha1 = "157f256e8bd019e55eea2c77bf80d158999a97f8"
libc = "glibc"
os = "linux"

    [[quarto.download]]
    sha256 = "a94fdc5b631dd9d8240f3d15490d7f4f4fdc36a4fd3f93699a733d5562800503"
    url = "https://github.com/JuliaBinaryWrappers/quarto_jll.jl/releases/download/quarto-v1.5.57+1/quarto.v1.5.57.aarch64-linux-gnu.tar.gz"
[[quarto]]
arch = "x86_64"
git-tree-sha1 = "e68bee4bb0c5f3be695cbee7da78e1f468b87d6a"
os = "macos"

    [[quarto.download]]
    sha256 = "f2399b1e1f29bdebfdfc831f45771ea9ccd71682740279e50159a06a2d44643d"
    url = "https://github.com/JuliaBinaryWrappers/quarto_jll.jl/releases/download/quarto-v1.5.57+1/quarto.v1.5.57.x86_64-apple-darwin.tar.gz"
[[quarto]]
arch = "x86_64"
git-tree-sha1 = "9fd191e22fef31c8d4909fb3c3944debf529ffdd"
libc = "glibc"
os = "linux"

    [[quarto.download]]
    sha256 = "61c9aee64e4acd6e989ecda3c414dbac101f85629f3a5a74541c099b47c33ae9"
    url = "https://github.com/JuliaBinaryWrappers/quarto_jll.jl/releases/download/quarto-v1.5.57+1/quarto.v1.5.57.x86_64-linux-gnu.tar.gz"
[[quarto]]
arch = "x86_64"
git-tree-sha1 = "42caf91eedff926b08564c748f64573b6eb73d8b"
os = "windows"

    [[quarto.download]]
    sha256 = "cdeed8ba61df09f6ff236a655f832de23ea65b2afd6af180233246706e44334b"
    url = "https://github.com/JuliaBinaryWrappers/quarto_jll.jl/releases/download/quarto-v1.5.57+1/quarto.v1.5.57.x86_64-w64-mingw32.tar.gz"
