# Autogenerated wrapper script for quarto_jll for x86_64-apple-darwin
export quarto

JLLWrappers.@generate_wrapper_header("quarto")
JLLWrappers.@declare_executable_product(quarto)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        quarto,
        "bin/quarto",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
