# Autogenerated wrapper script for quarto_jll for x86_64-w64-mingw32
export quarto

JLLWrappers.@generate_wrapper_header("quarto")
JLLWrappers.@declare_executable_product(quarto)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        quarto,
        "bin\\quarto.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
